import Head from "next/head";

export default function Home() {
  return (
    <div className="flex items-center justify-center min-h-screen">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Admin Template</title>
      </Head>
    </div>
  );
}
