import { useState } from "react";
import Head from "next/head";
import Card from "../components/Card";
import NumberInput from "../components/NumberInput";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [doorQuantity, setDoorQuantity] = useState(3);
  const [hasGift, setHasGift] = useState(1);

  return (
    <>
      <Head>
        <title>Lucky Door</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1>Lucky Door</h1>
        <div className={styles.cardBox}>
          <Card>
            <NumberInput
              text={"How many doors?"}
              value={doorQuantity}
              onChange={(newQuantity) => setDoorQuantity(newQuantity)}
            />
          </Card>
          <Card>
            <NumberInput
              text={"Gifed Door"}
              value={hasGift}
              onChange={(newGiftedDoor) => setHasGift(newGiftedDoor)}
            />
          </Card>
        </div>
        <div className={styles.buttonBox}>
          <button>Iniciar</button>
        </div>
      </div>
    </>
  );
}
