import { useState } from "react";
import Head from "next/head";
import Gift from "../components/Gift";
import Door from "../components/Door";
import DoorModel from "../model/DoorModel";

export default function Home() {
  const [p1, setP1] = useState(new DoorModel(1));
  return (
    <>
      <Head>
        <title>Lucky Door</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Door value={p1} onChange={(newDoor) => setP1(newDoor)} />
      </div>
    </>
  );
}
