import { useEffect, useState } from "react";
import { useChangeHighlight } from "../../../hooks/useChangeHighlight";
import { useCreateDoors } from "../../../hooks/useCreateDoors";
import { useRouter } from "next/router";
import Head from "next/head";
import Door from "../../../components/Door";
import Link from "next/link";
import DoorModel from "../../../model/DoorModel";
import styles from "../../../styles/Game.module.css";

export default function Game() {
  const router = useRouter();
  const [doors, setDoors] = useState<DoorModel[]>([]);
  const [isValidGame, setIsValidGame] = useState<boolean>(false);

  useEffect(() => {
    const doors = +router.query.doors;
    const giftedDoor = +router.query.hasGift;
    const validDoors = doors >= 3 && doors <= 10;
    const validGiftedDoor = giftedDoor >= 1 && giftedDoor <= doors;
    setIsValidGame(validDoors && validGiftedDoor);
  }, [doors]);

  useEffect(() => {
    const doors = +router.query.doors;
    const giftedDoor = +router.query.hasGift;
    setDoors(useCreateDoors(doors, giftedDoor));
  }, [router?.query]);

  return (
    <>
      <Head>
        <title>Lucky Door</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.doorContainer}>
          {isValidGame
            ? doors.map((door) => (
                <Door
                  key={door.doorNumber}
                  value={door}
                  onChange={(newDoor) => {
                    setDoors(useChangeHighlight(doors, newDoor));
                  }}
                />
              ))
            : "Invalid Game"}
        </div>
        <div className={styles.buttonBox}>
          <Link href={"/"}>
            <button>Retornar</button>
          </Link>
        </div>
      </div>
    </>
  );
}
