import Head from "next/head";
import Question from "../components/Question";
import styles from "../styles/Home.module.css";
import QuestionModel from "../../models/question";
import AnswerModel from "../../models/answer";

export default function Home() {
  const testQuestion = new QuestionModel(1, "Melhor cor?", [
    AnswerModel.wrongAnswer("Green"),
    AnswerModel.wrongAnswer("Red"),
    AnswerModel.wrongAnswer("Blue"),
    AnswerModel.rightAnswer("Black"),
  ]);
  return (
    <div className={styles.homeContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Question value={testQuestion} />
    </div>
  );
}
